### ISSUE TITLE
help wanted: I want to get custom ENV variable in mdev

### ISSUE THREAD

**Issue by ishanwenli** [brgl/busybox#1]
Hi, can you help me ?
I want to match MY_DEVICE_ID and then to exec some script, 
example in /etc/mdev.conf
`$MY_DEVICE_ID=201 root:root 660 @/bin/sh mount.sh`
But, it is not good.
when I use ACTION, it is okay,
`$ACTION=add root:root 660 @/bin/sh mount.sh `
that is good
I know the ACTION is system ENV variable, so, what different with them?
Is the mdev not to do any thing when receiving custom ENV variable?

Look forward to your reply,
thank you

**Comment by brgl** [comment]
I think you got confused, this is my private fork of the busybox repo.
